//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTVibrantStylingProvider, UIView;

@protocol SBDashBoardAdjunctItemHosting <NSObject>
- (UIView *)view;
- (struct CGSize)preferredContentSize;

@optional
- (void)setVibrantStylingProvider:(MTVibrantStylingProvider *)arg1;
- (void)setContainerSize:(struct CGSize)arg1;
@end

