//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSInvalidatable.h"
#import "SBSceneHandleObserver.h"

@class FBSDisplayConfiguration, FBSDisplayIdentity, FBScene, NSString, SBApplication, SBApplicationSceneHandle, _UIRootWindow;

@interface SBExternalDisplayPresenter : NSObject <SBSceneHandleObserver, BSInvalidatable>
{
    FBSDisplayIdentity *_identity;
    _Bool _invalidated;
    FBSDisplayConfiguration *_currentConfiguration;
    FBSDisplayConfiguration *_currentReportedConfiguration;
    SBApplication *_foregroundApp;
    SBApplicationSceneHandle *_foregroundAppSceneHandle;
    FBScene *_foregroundAppScene;
    unsigned long long _foregroundAppSequenceNumber;
    _UIRootWindow *_rootWindow;
    FBSDisplayConfiguration *_rootWindowConfiguration;
    SBApplicationSceneHandle *_presentationSceneHandle;
    FBScene *_presentationScene;
    FBSDisplayConfiguration *_presentationSceneConfiguration;
    _Bool _hasEnqueuedPresentationUpdate;
}

- (void).cxx_destruct;
- (void)sceneHandle:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 transitionContext:(id)arg3;
- (void)sceneHandle:(id)arg1 didUpdateContentState:(long long)arg2;
- (void)_enqueuePresentationUpdate;
- (void)_ensureResolution:(struct CGSize)arg1 overscanCompensation:(long long)arg2 withPostChangeBlock:(CDUnknownBlockType)arg3;
- (id)_createUpdateTransaction;
- (id)updateToConfiguration:(id)arg1 withForegroundApp:(id)arg2;
- (void)invalidate;
- (id)initWithDisplay:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

