//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBBiometricMonitorUI, SBLockScreenBiometricFailureSettings;

@interface SBLockScreenPearlSettings : SBUISettings
{
    SBBiometricMonitorUI *_monitorUI;
    _Bool _pearlDebugUIEnabled;
    _Bool _showScanningStateOnLockScreen;
    _Bool _showScanningStateDuringFaceDetect;
    SBLockScreenBiometricFailureSettings *_failureSettings;
    double _minimumDurationBeforeShowingScanningState;
}

+ (id)settingsControllerModule;
@property(nonatomic) double minimumDurationBeforeShowingScanningState; // @synthesize minimumDurationBeforeShowingScanningState=_minimumDurationBeforeShowingScanningState;
@property(nonatomic) _Bool showScanningStateDuringFaceDetect; // @synthesize showScanningStateDuringFaceDetect=_showScanningStateDuringFaceDetect;
@property(nonatomic) _Bool showScanningStateOnLockScreen; // @synthesize showScanningStateOnLockScreen=_showScanningStateOnLockScreen;
@property(retain, nonatomic) SBLockScreenBiometricFailureSettings *failureSettings; // @synthesize failureSettings=_failureSettings;
@property(nonatomic) _Bool pearlDebugUIEnabled; // @synthesize pearlDebugUIEnabled=_pearlDebugUIEnabled;
- (void).cxx_destruct;
- (void)_updateDebugUI;
- (CDStruct_ded0333f)proudLockControllerViewControllerConfiguration;
- (void)setDefaultValues;
- (void)dealloc;
- (id)initWithDefaultValues;

@end

