//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBMainDisplayWorkspaceAppInteractionEventSourceObserving.h"

@class NSString, SBFloatingDockBehaviorAssertion;

@interface SBSetupManager : NSObject <SBMainDisplayWorkspaceAppInteractionEventSourceObserving>
{
    _Bool _inSetupMode;
    _Bool _inSetupModeReadyToExit;
    SBFloatingDockBehaviorAssertion *_inSetupFloatingDockBehaviorAssertion;
}

+ (id)sharedInstance;
@property(nonatomic, getter=isInSetupModeReadyToExit) _Bool inSetupModeReadyToExit; // @synthesize inSetupModeReadyToExit=_inSetupModeReadyToExit;
- (void).cxx_destruct;
- (void)eventSource:(id)arg1 didBeginTransitionToMode:(long long)arg2 withLayoutState:(id)arg3 activatingElement:(id)arg4 triggeredBy:(long long)arg5;
- (void)_clearFloatingDockAssertion;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (void)postLaunchCompleteNotificationForSetup;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

